import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import API from "../api/axios";
import toast from "react-hot-toast";

export default function CreateInterview() {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [done,    setDone]    = useState(null);
  const [form, setForm] = useState({
    jobTitle: "", jobDescription: "", skills: "",
    experienceLevel: "mid", numQuestions: "8",
  });
  const set = (k) => (e) => setForm({ ...form, [k]: e.target.value });

  const submit = async (e) => {
    e.preventDefault();
    if (!form.jobTitle || !form.jobDescription) return toast.error("Job title and description are required.");
    setLoading(true);
    try {
      const { data } = await API.post("/interview/create", {
        ...form,
        skills: form.skills.split(",").map(s => s.trim()).filter(Boolean),
        numQuestions: Number(form.numQuestions),
      });
      setDone(data);
      toast.success(`${data.questionsCount} questions generated by AI!`);
    } catch (err) {
      toast.error(err.response?.data?.message || "Failed to create interview.");
    } finally { setLoading(false); }
  };

  const copyLink = () => {
    navigator.clipboard.writeText(done.inviteLink);
    toast.success("Invite link copied!");
  };

  return (
    <div style={{ padding: 28, maxWidth: 700 }}>
      <div className="mb6">
        <h2 className="h2">Create AI Interview</h2>
        <p className="muted sm mt1">Paste the job description — AI will auto-generate questions</p>
      </div>

      {done ? (
        <div className="card">
          <div style={{ fontSize: 40, marginBottom: 12 }}>🎉</div>
          <h3 className="h3 mb2">Interview Created!</h3>
          <p className="muted sm mb4">{done.questionsCount} questions generated. Share the link with candidates.</p>
          <div style={{ background: "var(--surface2)", border: "1px solid var(--border)", borderRadius: "var(--r)", padding: "12px 14px", marginBottom: 14, fontFamily: "'JetBrains Mono',monospace", fontSize: 12, wordBreak: "break-all" }}>
            {done.inviteLink}
          </div>
          <div className="fxc gap3">
            <button className="btn btn-primary" onClick={copyLink}>Copy Invite Link</button>
            <button className="btn btn-outline" onClick={() => navigate(`/interviews/${done._id}`)}>View Interview</button>
            <button className="btn btn-ghost" onClick={() => { setDone(null); setForm({ jobTitle: "", jobDescription: "", skills: "", experienceLevel: "mid", numQuestions: "8" }); }}>Create Another</button>
          </div>
        </div>
      ) : (
        <div className="card">
          <form onSubmit={submit}>
            <div className="input-group">
              <label className="lbl">Job Title *</label>
              <input className="inp" required placeholder="e.g. Senior React Developer" value={form.jobTitle} onChange={set("jobTitle")} />
            </div>
            <div className="input-group">
              <label className="lbl">Required Skills (comma-separated)</label>
              <input className="inp" placeholder="React, Node.js, MongoDB, REST APIs" value={form.skills} onChange={set("skills")} />
            </div>
            <div className="row2">
              <div className="input-group">
                <label className="lbl">Experience Level</label>
                <select className="sel" value={form.experienceLevel} onChange={set("experienceLevel")}>
                  <option value="fresher">Fresher (0–2 yrs)</option>
                  <option value="mid">Mid-level (2–5 yrs)</option>
                  <option value="senior">Senior (5+ yrs)</option>
                </select>
              </div>
              <div className="input-group">
                <label className="lbl">Number of Questions</label>
                <select className="sel" value={form.numQuestions} onChange={set("numQuestions")}>
                  <option value="5">5 questions</option>
                  <option value="8">8 questions</option>
                  <option value="10">10 questions</option>
                  <option value="12">12 questions</option>
                </select>
              </div>
            </div>
            <div className="input-group">
              <label className="lbl">Job Description * (paste full JD — AI reads this)</label>
              <textarea className="txta" required style={{ minHeight: 140 }}
                placeholder="Paste the complete job description here. The AI will analyze it and generate relevant technical and behavioral questions automatically..."
                value={form.jobDescription} onChange={set("jobDescription")} />
            </div>
            <div style={{ background: "var(--purple-l)", border: "1px solid #c4bef8", borderRadius: "var(--r)", padding: "10px 14px", marginBottom: 16, fontSize: 12, color: "var(--purple)" }}>
              ✦ AI will generate {form.numQuestions} questions — 50% technical, 25% behavioral, 25% situational. Uses 1 credit.
            </div>
            <button className="btn btn-primary btn-lg btn-full" disabled={loading} type="submit">
              {loading ? <><span className="spin" /> Generating with AI...</> : "Generate Interview with AI"}
            </button>
          </form>
        </div>
      )}
    </div>
  );
}
